### ISSUE TITLE
Video Recordings

### ISSUE THREAD

**Issue by jakeret** [SwissPy/swisspycon#36] opened 2015-11-30 08:29 UTC
If we going to share the talks on Youtube we need an account. Maybe the person who is going to edit/upload the videos could open it to make sure that he/she has the account credentials

**Comment by dbrgn** [comment] 2015-11-30 10:12
First of all we need to know how we record everything :) Simplest thing would probably be a DSLR and a separate audio recording.

We can discuss that at the meeting (#37).

**Comment by dbrgn** [comment] 2016-01-27 17:00
Duplicate of #49.

**Closed as completed by dbrgn** 2016-01-27 17:00 UTC
Labels: on-site
